// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AnimatedComponent: typeof import('./src/components/AnimatedComponent.vue')['default']
    ContactForm: typeof import('./src/components/ContactForm.vue')['default']
    Container: typeof import('./src/components/Container.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    FullPage: typeof import('./src/components/FullPage.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    Nav: typeof import('./src/components/Nav.vue')['default']
    Notification: typeof import('./src/components/Notification.vue')['default']
    ProjectCard: typeof import('./src/components/ProjectCard.vue')['default']
    ScrollMouse: typeof import('./src/components/ScrollMouse.vue')['default']
    ScrollTop: typeof import('./src/components/ScrollTop.vue')['default']
    SectionContact: typeof import('./src/components/SectionContact.vue')['default']
    SectionHero: typeof import('./src/components/SectionHero.vue')['default']
    SectionProfile: typeof import('./src/components/SectionProfile.vue')['default']
    SectionProjects: typeof import('./src/components/SectionProjects.vue')['default']
    SectionServices: typeof import('./src/components/SectionServices.vue')['default']
    SectionStack: typeof import('./src/components/SectionStack.vue')['default']
    ServiceCard: typeof import('./src/components/ServiceCard.vue')['default']
    Socials: typeof import('./src/components/Socials.vue')['default']
    Text: typeof import('./src/components/Text.vue')['default']
    Title: typeof import('./src/components/Title.vue')['default']
  }
}

export {}
