// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Header: typeof import('./src/components/Header.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    Page1: typeof import('./src/components/Page1.vue')['default']
    Socials: typeof import('./src/components/Socials.vue')['default']
  }
}

export {}
